spring:
  config:
    activate:
      on-profile: test
  data:
    web:
      pageable:
        default-page-size: 20
        one-indexed-parameters: true
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    username: dbtest
    password: dbtestpassword
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
  flyway:
    enabled: false
  jackson:

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location:

cloud:
  aws:
    credentials:
      accessKey: AKIARSMJT6KAIKVJPVM6
      secretKey: 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
    sqs:
      mos-eth-factory: https://sqs.ap-northeast-2.amazonaws.com/108199670400/local-mos-eth-factory.fifo
      mos-eth-nft: https://sqs.ap-northeast-2.amazonaws.com/108199670400/local-mos-eth-nft.fifo
      mos-eth-primary-market: https://sqs.ap-northeast-2.amazonaws.com/108199670400/local-mos-eth-primary-market.fifo
      mos-eth-secondary-market: https://sqs.ap-northeast-2.amazonaws.com/108199670400/local-mos-eth-secondary-market.fifo
      mos-eth-dead-letter: https://sqs.ap-northeast-2.amazonaws.com/108199670400/local-mos-eth-dead-letter.fifo
      mos-notification: https://sqs.ap-northeast-2.amazonaws.com/108199670400/local-mos-notification.fifo
    s3:
      bucket: mos-s3-test
      image-dir: images/
      template-dir: template/
    region:
      static: ap-northeast-2
    stack:
      auto: false

notification:
  email:
    supportEmail: support@mosaicsquare.io
    supportName: Mosaic Square
  service:
    pusher:
      appId: 1429073
      appKey: 470ba071446751150c88
      appSecret: f2119ac2dc286e7879a9
      appCluster: ap3
      eventId: mosaic-square-notification-service

logging:
  level:
    org.hibernate.type: TRACE
    org.springframework: INFO
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
    com.mosaicsquare: DEBUG
    kotlin.reflect.jvm.internal: DEBUG
  config: classpath:log4j2-test.yml
