spring:
  config:
    activate:
      on-profile: local
  data:
    web:
      pageable:
        default-page-size: 20
        one-indexed-parameters: true
  datasource:
    url: jdbc:mysql://localhost:3306/mosaic_square?serverTimezone=UTC&characterEncoding=UTF-8
    username: mosaic
    password: p@ssw0rd
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        use_sql_comments: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location:

cloud:
  aws:
    credentials:
      accessKey: AKIARSMJT6KAIKVJPVM6
      secretKey: 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
    sqs:
      mos-eth-factory: https://sqs.ap-northeast-2.amazonaws.com/108199670400/local-mos-eth-factory.fifo
      mos-eth-nft: https://sqs.ap-northeast-2.amazonaws.com/108199670400/local-mos-eth-nft.fifo
      mos-eth-primary-market: https://sqs.ap-northeast-2.amazonaws.com/108199670400/local-mos-eth-primary-market.fifo
      mos-eth-secondary-market: https://sqs.ap-northeast-2.amazonaws.com/108199670400/local-mos-eth-secondary-market.fifo
      mos-eth-dead-letter: https://sqs.ap-northeast-2.amazonaws.com/108199670400/local-mos-eth-dead-letter.fifo
      mos-notification: https://sqs.ap-northeast-2.amazonaws.com/108199670400/local-mos-notification.fifo
    s3:
      bucket: mos-s3-test
      image-dir: images/
      template-dir: template/
    region:
      static: ap-northeast-2
    stack:
      auto: false

notification:
  email:
    supportEmail: support@mosaicsquare.io
    supportName: Mosaic Square
  service:
    pusher:
      appId: 1429073
      appKey: 470ba071446751150c88
      appSecret: f2119ac2dc286e7879a9
      appCluster: ap3
      eventId: mosaic-square-notification-service

logging:
  level:
    org.hibernate.type: TRACE
    org.springframework: INFO
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: TRACE
    com.mosaicsquare: DEBUG
  config: classpath:log4j2-local.yml
